global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana:3000']

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  - job_name: mlflow
    metrics_path: /
    scheme: http
    static_configs:
      - targets: ['mlflow:5000']

  - job_name: minio
    metrics_path: /minio/v2/metrics/node
    static_configs:
      - targets: ['minio:9000']

  - job_name: superset
    metrics_path: /health
    static_configs:
      - targets: ['superset:8088']


